"""Generate reproducible test structures for the Open Docking test suite.

Real receptor structures cannot be committed (and downloading them makes tests
network-dependent), so this module builds a **small, physically sensible**
receptor and a handful of ligands from scratch with RDKit.

The receptor is a carbon "cage" with two polar oxygens, which is enough to
exercise every code path that matters:

* apolar and polar receptor atoms, so all four map slots are populated;
* a real pocket, so the search has somewhere to converge;
* known geometry, so assertions can be about *physics* (the ligand ends up in
  the pocket, the energy is negative) rather than about a memorised number.

The ligands are real drug-like molecules with known rotatable-bond counts, which
lets the torsion perception be tested against chemistry rather than against a
fixture that happens to match the implementation.

Run directly to write the files::

    python -m odockmcode.tests.make_data [output-dir]
"""

from __future__ import annotations

import math
import sys
from pathlib import Path

import numpy as np

__all__ = ["make_receptor_pdb", "make_ligands", "write_all", "LIGANDS"]

#: SMILES for the test ligands, chosen to span the torsion and polarity range.
LIGANDS: dict[str, str] = {
    # Rigid: no rotatable bonds, tests the rigid-body path.
    "benzene": "c1ccccc1",
    # One rotatable bond.
    "toluene": "Cc1ccccc1",
    # Two rotatable bonds, one hydroxyl donor.
    "phenol": "Oc1ccccc1",
    # Flexible drug-like molecule: 5 rotatable bonds, mixed donors/acceptors.
    "ibuprofen": "CC(C)Cc1ccc(cc1)C(C)C(=O)O",
    # A hydrogen-bond-rich flexible ligand, for hbond map coverage.
    "salbutamol": "CC(C)(C)NCC(O)c1ccc(O)c(CO)c1",
}

# --- Synthetic receptor geometry -------------------------------------------
# An 18-membered crown-ether-like macrocycle: six -O-CH2-CH2- units on a
# circle, so the ring is a *single* bonded fragment with a real cavity in the
# middle. Six hydroxyls are attached to alternating ring carbons, alternating
# above and below the ring plane, which gives the receptor hydrogen-bond
# donors as well as acceptors.
_RECEPTOR_RING_SIZE = 18
_RECEPTOR_BOND = 1.5  # Ångström, so RDKit perceives a proper covalent graph
_RECEPTOR_C = 1.43  # C-O
_RECEPTOR_OH = 0.96  # O-H
#: Ring indices (0-based) that carry a hydroxyl.
_RECEPTOR_OH_SITES = (1, 4, 7, 10, 13, 16)


def _ring_radius() -> float:
    """Radius of a regular ring whose adjacent atoms sit ``_RECEPTOR_BOND`` apart."""
    return _RECEPTOR_BOND / (2.0 * math.sin(math.pi / _RECEPTOR_RING_SIZE))


def _mol(smiles: str):
    from rdkit import Chem
    from rdkit.Chem import AllChem

    mol = Chem.MolFromSmiles(smiles)
    if mol is None:
        raise ValueError(f"RDKit could not parse {smiles!r}")
    mol = Chem.AddHs(mol)
    params = AllChem.ETKDGv3()
    params.randomSeed = 0x0D0C
    if AllChem.EmbedMolecule(mol, params) != 0:
        # Fall back to a random embedding rather than failing the whole run.
        params.useRandomCoords = True
        if AllChem.EmbedMolecule(mol, params) != 0:
            raise ValueError(f"could not generate 3-D coordinates for {smiles!r}")
    try:
        AllChem.MMFFOptimizeMolecule(mol, maxIters=2000)
    except Exception:
        pass
    return mol


def make_receptor_pdb() -> str:
    """Build a small host molecule as PDB text.

    The receptor is an 18-membered macrocycle — six ``-O-CH2-CH2-`` units laid
    out on a circle whose adjacent atoms are exactly one C-C bond apart, so
    RDKit perceives a single connected covalent graph. Six of the ring carbons
    carry a hydroxyl, alternating above and below the ring plane; the polar
    hydrogens are written out explicitly so the receptor can act as a
    hydrogen-bond *donor* as well as an acceptor.

    It is not a protein, but it has the properties a docking test needs: one
    connected fragment (so fragment selection keeps all of it), apolar and polar
    atoms (so all four map slots are populated), a genuine cavity, and
    coordinates centred on the origin so a box at (0, 0, 0) is meaningful.
    """
    lines = [
        "REMARK   1 SYNTHETIC TEST RECEPTOR",
        "REMARK   1 Generated by odockmcode.tests.make_data - not a real structure",
    ]
    radius = _ring_radius()
    coords: list[tuple[str, str, float, float, float]] = []

    n_c = 0
    n_o = 0
    for i in range(_RECEPTOR_RING_SIZE):
        theta = i * 2.0 * math.pi / _RECEPTOR_RING_SIZE
        x, y = radius * math.cos(theta), radius * math.sin(theta)
        if i % 3 == 0:
            n_o += 1
            coords.append((f"O{n_o}", "O", x, y, 0.0))
        else:
            n_c += 1
            coords.append((f"C{n_c}", "C", x, y, 0.0))

    n_exo_o = 0
    n_h = 0
    for k, i in enumerate(_RECEPTOR_OH_SITES):
        theta = i * 2.0 * math.pi / _RECEPTOR_RING_SIZE
        x, y = radius * math.cos(theta), radius * math.sin(theta)
        sign = 1.0 if k % 2 == 0 else -1.0
        n_exo_o += 1
        n_h += 1
        coords.append((f"O{n_o + n_exo_o}", "O", x, y, sign * _RECEPTOR_C))
        coords.append((f"H{n_h}", "H", x, y, sign * (_RECEPTOR_C + _RECEPTOR_OH)))

    for serial, (name, element, x, y, z) in enumerate(coords, start=1):
        lines.append(_atom_line(serial, name, element, x, y, z, "CRW", 1))
    lines.append("END")
    return "\n".join(lines) + "\n"


def _atom_line(
    serial: int,
    name: str,
    element: str,
    x: float,
    y: float,
    z: float,
    resname: str,
    resseq: int,
) -> str:
    """One standard 78-column ``ATOM`` record.

    ``element`` goes in columns 77-78, which is where RDKit's PDB reader looks
    for it; putting the atom *name* there instead would make the reader guess.
    """
    return (
        f"ATOM  {serial:>5} {name:<4} {resname:>3} A{resseq:>4}    "
        f"{x:>8.3f}{y:>8.3f}{z:>8.3f}{1.00:>6.2f}{0.00:>6.2f}"
        f"{'':>10}{element:>2}"
    )


def make_ligands() -> dict[str, str]:
    """Return ``{name: smiles}`` for the test ligand set."""
    return dict(LIGANDS)


def make_solid_receptor_pdbqt(extent: float = 10.0, pitch: float = 1.6) -> str:
    """A cube of space with no room in it, as receptor PDBQT.

    Carbons on a simple-cubic lattice filling a cube of side ``extent``. The
    widest void in such a lattice is the cube centre, at
    ``pitch * sqrt(3) / 2`` from the eight surrounding atoms — 1.39 Å at the
    default pitch — so no ligand atom can be placed anywhere in the box without
    overlapping something. That is what makes it useful: it is the one receptor
    that provably *cannot* yield a physically possible pose, so it exercises
    the clash-reporting path deterministically instead of hoping a weak search
    happens to bury the ligand.
    """
    n_axis = int(extent / pitch) + 1
    half = (n_axis - 1) * pitch / 2.0
    lines = []
    serial = 0
    for i in range(n_axis):
        for j in range(n_axis):
            for k in range(n_axis):
                serial += 1
                lines.append(
                    _atom_line(
                        serial,
                        f"C{serial}",
                        "C",
                        -half + pitch * i,
                        -half + pitch * j,
                        -half + pitch * k,
                        "LIG",
                        1,
                    )
                )
    return "\n".join(lines) + "\nEND\n"


def write_all(directory: str | Path) -> dict[str, Path]:
    """Write every test structure into ``directory``.

    Returns a mapping of logical name to written path.
    """
    from ..prep import prepare_ligand, prepare_receptor

    out = Path(directory)
    out.mkdir(parents=True, exist_ok=True)
    written: dict[str, Path] = {}

    rec_pdb = out / "receptor.pdb"
    rec_pdb.write_text(make_receptor_pdb(), encoding="utf-8")
    written["receptor_pdb"] = rec_pdb

    # The prepared receptor, through the real RDKit path.
    import tempfile

    with tempfile.TemporaryDirectory() as tmp:
        raw = Path(tmp) / "receptor.pdb"
        raw.write_text(make_receptor_pdb(), encoding="utf-8")
        rec_pdbqt = out / "receptor.pdbqt"
        rec_pdbqt.write_text(prepare_receptor(raw), encoding="utf-8")
        written["receptor_pdbqt"] = rec_pdbqt

    # Ligands: an SDF (the natural RDKit format) and, through the real
    # preparation path, the tables the engine consumes.
    from rdkit import Chem

    sdf_path = out / "ligands.sdf"
    writer = Chem.SDWriter(str(sdf_path))
    for name, smiles in LIGANDS.items():
        mol = _mol(smiles)
        mol.SetProp("_Name", name)
        writer.write(mol)
    writer.close()
    written["ligands_sdf"] = sdf_path

    lig_dir = out / "ligands"
    lig_dir.mkdir(exist_ok=True)
    from ..core import Ligand
    from ..pdbqt_writer import ligand_to_pdbqt

    for name, smiles in LIGANDS.items():
        # One SDF per ligand, so the CLI can be driven file by file. Re-embed
        # rather than re-reading `ligands.sdf`: ETKDGv3 with a fixed seed makes
        # this deterministic, and it avoids depending on record ordering.
        source = out / f"{name}.sdf"
        mol = _mol(smiles)
        mol.SetProp("_Name", name)
        single = Chem.SDWriter(str(source))
        single.write(mol)
        single.close()

        # Also produce a prepared-ligand PDBQT so the CLI has something to eat.
        elements, charges, coords, bonds, names = prepare_ligand(source)
        ligand = Ligand.from_arrays(elements, charges, coords, bonds, names)
        dest = lig_dir / f"{name}.pdbqt"
        dest.write_text(ligand_to_pdbqt(ligand, coords, names), encoding="utf-8")
        written[f"ligand_{name}"] = dest

    return written


def main(argv: list[str] | None = None) -> int:  # pragma: no cover
    args = list(sys.argv[1:] if argv is None else argv)
    directory = args[0] if args else "odockmcode-test-data"
    written = write_all(directory)
    for key, path in written.items():
        print(f"{key:24s} -> {path}")
    return 0


if __name__ == "__main__":  # pragma: no cover
    raise SystemExit(main())
